title: Hacked Jekyll
description: Jekyll microtheme that looks like JSON
baseurl: /hacked-jekyll
url: https://invicinity.github.io

theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  